name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: |
          cd cicd
          flutter pub get

      - name: Analyze code
        run: |
          cd cicd
          flutter analyze

      - name: Run tests
        run: |
          cd cicd
          flutter test

  build_appbundle:
    name: Build Flutter (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: |
          cd cicd
          flutter pub get

      - name: Clean build artifacts
        run: |
          cd cicd
          flutter clean

      - name: Build app bundle
        run: |
          cd cicd
          flutter build appbundle
